### ISSUE TITLE
Readme on this repositorie? 

### ISSUE THREAD

**Issue by doobdo** [Kampfgnom/homeassistant-niceflors#1]
While trying to control my Nice Shutter, I found your repositories. Do yo plan to create a Readme? I tried to implement your integration to HA without success. I'll be glad to help with this repo if possible. Cheers

**Comment by Jev1337** [comment]
Same, I haven't found a way to configure this properly

**Comment by Jev1337** [comment]
Update, I opened #2 a pull request, you can find a readme. I successfully managed to make it work

**Comment by niklas-sparfeld** [comment]
Hey! Sorry for taking *ages* to answer 🙈 I'm not really an open source maintainer. I just put this out in case *maybe* somebody will find it useful. I never imagined that somebody would manage to get it into a usable state 😅 

So, kudos and thanks! 👍 I'm really happy that at there are really people who could use this.

I've just added the deprecation fix myself and will comment on your PR.

**Comment by niklas-sparfeld** [comment]
#2 closes this issue. Feel free to re-open if you need some support. Maybe I can help :)
